const RouteURL = {
    //For maintain staging and production
    webMode: `local`,
    // webMode: `production`,
    version: "V 3.43",


    login_api: "/admin/login",
    get_all_role: "/admin/get-all-role",
    add_role: "/admin/add-role",
    edit_role: "/admin/edit-role",
    delete_role: "/admin/delete-role",
    update_admin: "/admin/update-admin",
    create_admin: "/admin/create-admin",
    get_all_role_by_admin: "/admin/get-all-role-by-admin",
    get_all_menu: "/admin/get-all-menu",
    get_filter_player_list: "/admin/get-filter-player-list",
    get_profile_details: "/admin/get-profile-details",
    get_account_statement: "/admin/get-account-statement",
    add_cash_account_statement: "/admin/add-cash-account-statement",
    bonus_account_statement: "/admin/bonus-account-statement",
    tax_config: "/admin/tax-config",
    verifyLoginOtp: "/client/verify-otp",
    forgotPassword: "/client/forget-password-generate-otp",
    verifyForgetPasswordOtp: "/client/forget-password-verify-otp",
    resetPassword: "/client/forget-password-verify-token",
    changePassword: "/client/change-password",

    updateClientPassword: "update-client-password",

    addUpdateGameCategory: "add-update-game-category",
    accountWisePlayerList: "account-wise-player-list",
    accountTransactionHistory: "client/account-transaction-history",
    accountWisePlayerTransactionHistory: "client/account-wise-gameplay-transaction-history",
    gameList: "/client/all-games",
    gameStatusChange: "client/update-game-status",
    AllGameCategory: "client/all-game-category",
    levelList: "/client/list-level",
    regionList: "/client/list-region",
    addPlayer: "client/add-player",
    updatePlayer: "client/update-player",
    deletePlayer: "client/delete-player",
    allPlayerList: "client/list-player",
    updatePlayerStatus: "client/player-status-update",

    addClientAccount: "/client/add-account",
    UpdateClientAccount: "/client/update-account",
    clientDetails: "client/client-details",
    clientAccountsList: "client/list-account",
    updateAccountStatus: "/client/update-account-status",
    updateClientStatus: "/client/update-client-status",
    clientAccountDetails: "/client/account-details",

    clientAccountWiseCurrencyList: "client/list-account-all",
    tranferPlayerBalance: "client/player-balance-transfer",
    PlayerDetails: "client/player-details",
    ProviderList: "client/assigned-provider-list-by-account",
    PlayerTransactionDetails: "/client/player-transaction-details",
    AccountWiseGameList: "client/assigned-game-list-by-account",
    clientList: "client/list-client",
    AddEditClient: "client/add-edit-client",

    transferBalancetoClientAccount: "/client/client-balance-transfer",
    playerTransactionSummary: "/client/player-wallet-transaction-list",

    getTechnicalAccountDetails: "client/get-account-technicals",
    saveAccountTechnicals: "client/save-account-technicals",
    allClientList: "client/list-sub-client",
    allProviderList: "client/all-providers",
    clientwiseAccountsList: "client/list-sub-client-account",
    assignDeassignProvider: "client/assign-deassign-provider-to-sub-client",
    providerWiseReport: "client/provider-wise-report",
    assignDeassignGames: "client/assign-deassign-games-to-sub-client",
    allGamesWithoutPagination: "client/all-games-without-pagination",
    allGamesWithPagination: "client/all-games-with-pagination",
    gameWiseReport: "/client/game-wise-report",
    categoryWiseReport:"/client/game-category-wise-report",
    WalletTransactionReport:"/client/wallet-transaction-report",

    accountWiseWalletBalance: "/client/account-details-by-account-id",
    allProviderListWithPagination: "client/all-providers-with-pagination",
}
export default RouteURL;

